# **A.1D NumPy Array**

***1.Write a program to create a 1D NumPy array with five elements entered by the user.***

In [2]:
import numpy as np
arr=np.array([int(input("enter the element")) for i in range(5)])
print(arr)

enter the element10
enter the element20
enter the element30
enter the element40
enter the element60
[10 20 30 40 60]


***2.Write a program to find the length of a 1D NumPy array.***


In [3]:
arr=np.array([10,20,30,40])
print(len(arr))

4


***3.Write a program to access the first, middle, and last element of a NumPy array.***


In [4]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(len(arr)/2)
print(arr[-1])

10
2.5
50


***4.Write a program to slice a NumPy array from index 2 to 5.***


In [5]:
arr=np.array([10,20,30,40,50])
print(arr[2:6])

[30 40 50]


***5.Write a program to print all elements of a NumPy array using a loop.***


In [6]:
arr = np.array([10, 20, 30, 40])
for i in arr:
    print(i)



10
20
30
40


***6.Write a program to add 10 to each element of a NumPy array.***


In [7]:
arr=np.array([10,20,30,40])
print(arr+10)

[20 30 40 50]


***7.Write a program to find the sum and average of elements in a 1D NumPy array.***




In [8]:
arr = np.array([10, 20, 30, 40])
print("Sum:", np.sum(arr))
print("Average:", np.mean(arr))

Sum: 100
Average: 25.0


***8.Write a program to find the maximum and minimum value in a NumPy array.***


In [9]:
arr = np.array([5, 2, 9, 1, 7])
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))


Maximum: 9
Minimum: 1


***9.Write a program to reverse a NumPy array using slicing.***

In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])

[5 4 3 2 1]


***10.Write a program to check whether a specific element exists in a NumPy array.***


In [12]:
arr = np.array([10, 20, 30, 40])
x = int(input("enter the num"))
if x in arr:
    print("Element exists")
else:
    print("Element does not exist")

enter the num30
Element exists


## ***B. 2D NumPy Array Questions***


***11.Write a program to create a 2D NumPy array of size 3×3 and display it.***

In [13]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


***12.Write a program to find the shape of a 2D NumPy array.***

In [14]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Shape:", arr.shape)

Shape: (2, 3)


***13.Write a program to access a specific element from a 2D array using row and column index.***

In [15]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[1, 2])

60


***14.Write a program to extract the first row and first column from a 2D NumPy array.***


In [22]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[0:4, 0: 4])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***15.Write a program to slice a 2D NumPy array to get a sub-matrix.***

In [20]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
sub_matrix = arr[0:2, 1:3]
print(sub_matrix)


[[2 3]
 [5 6]]


***16.Write a program to calculate the sum of all elements in a 2D NumPy array.***


In [24]:
arr = np.array([
    [1, 2],
    [3, 4]
])
print( "Sum:", np.sum(arr))

Sum: 10


***17.Write a program to calculate row-wise sum of a 2D NumPy array.***


In [25]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Row-wise Sum:", np.sum(arr, axis=1))

Row-wise Sum: [ 6 15]


***18.Write a program to calculate column-wise average of a 2D NumPy array***


In [27]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("column-wise Average:", np.mean(arr, axis=0))

column-wise Average: [2.5 3.5 4.5]


***19.Write a program to multiply each element of a 2D NumPy array by 2.***

In [28]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


***20.Write a program to find the maximum value from each row of a 2D NumPy array.***

In [29]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(np.max(arr,axis=1))

[3 6 9]
