**1.You are given a NumPy array of student marks. Write a program to extract marks greater than the class average.**

In [ ]:
import numpy as np
stud_marks=np.array([10,54,67,47,76,89,54,56])
class_avg=np.mean(stud_marks)
result=stud_marks[stud_marks>class_avg]
print("class average:",class_avg)
print("marks greater than class average:",result)

class average: 56.625
marks greater than class average: [67 76 89]


***2.A company stores daily sales data in a NumPy array. Write a program to find days where sales were higher than 50,000.***

In [ ]:
sales=np.array([350000,65000,77000,45000,54000])
high_sales_days=sales[sales>50000]
print(high_sales_days)

[350000  65000  77000  54000]


***3.Given a NumPy array of temperatures in Celsius, write a program to convert all values to Fahrenheit using vectorized operations***

In [ ]:
celsius=np.array([45,35,23,45,65])
fehrenheit=(celsius*9/5)+32
print(fehrenheit)

[113.   95.   73.4 113.  149. ]


***4.A NumPy array contains employee working hours for a week. Write a program to find employees who worked more than 40 hours.***

In [ ]:
hours=np.array([60,67,76,46,87,67])
result=hours[hours>40]
print(result)

[60 67 76 46 87 67]


***5.Given a NumPy array of product prices, write a program to apply a 10 percent discount on prices greater than 1,000.***

In [ ]:
prices=np.array([3400,4500,3400,2400,4600],dtype=float)
prices[prices>1000]*=0.9
print(prices)

[3060. 4050. 3060. 2160. 4140.]


In [ ]:
#6.

***8.A NumPy array contains monthly expenses. Write a program to identify expenses that are above the median value.***


In [ ]:
expences=np.array([45000,67000,30000,5600,7000])
med=np.median(expences)
result=expences[expences>median]
print(med)
print(result)

30000.0
[45000 67000]


***9.A 2D NumPy array represents sales data of products across different regions. Write a program to find the region with the highest total sales.***

In [ ]:
sales=np.array([
    [2000,3000,4350],
    [3450,3540,4560],
    [4503,5468,4567]
])
result=np.sum(sales,axis=1)
best_region=np.argmax(result)

print(np.max(result))



14538


***10.Given a NumPy array of sensor readings, write a program to detect and extract all abnormal readings that are more than 2 times the mean value.***




In [ ]:
import numpy as np
readings = np.array([10, 12, 11, 13, 50, 14, 12])
mean_val = np.mean(readings)
abnormal = readings[readings > 2 * mean_val]
print("Abnormal readings:", abnormal)


Abnormal readings: [50]


***11.A NumPy array contains salary data of employees. Write a program to apply tax rules:***
Salary above 50,000 → deduct 10 percent
Salary above 1,00,000 → deduct 20 percent


In [ ]:
salary = np.array([30000, 60000, 120000, 80000],dtype=float)
final_salary = salary.copy()
final_salary[salary > 100000] *= 0.8
final_salary[(salary > 50000) & (salary <= 100000)] *= 0.9
print("Salary after tax:", final_salary)


Salary after tax: [30000. 54000. 96000. 72000.]


***12.Given a 2D NumPy array of student marks, write a program to find how many students failed in each subject.***

In [ ]:
marks = np.array([
    [40, 30, 50],
    [20, 60, 70],
    [33, 25, 80],
    [50, 45, 30]
])
failed_count = np.sum(marks < 35, axis=0)
print("Failed students in each subject:", failed_count)


Failed students in each subject: [2 2 1]


***13.A NumPy array contains website response times in milliseconds. Write a program to count how many requests exceeded the acceptable threshold.***


In [ ]:
response_times = np.array([120, 250, 400, 180, 600, 90])
threshold = 300
count = np.sum(response_times > threshold)
print("Requests exceeding threshold:", count)


Requests exceeding threshold: 2


***14.Given a NumPy array of daily profit and loss values, write a program to separate profit days and loss days using boolean indexing.***

In [ ]:
profit_loss = np.array([500, -200, 300, -100, 0, 400, -50])
profit_days = profit_loss[profit_loss > 0]
loss_days = profit_loss[profit_loss < 0]
print("Profit days:", profit_days)
print("Loss days:", loss_days)


Profit days: [500 300 400]
Loss days: [-200 -100  -50]


***15.A 2D NumPy array represents attendance of employees where 1 means present and 0 means absent. Write a program to calculate attendance percentage of each employee.***

In [ ]:
attendance = np.array([
    [1, 1, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [1, 1, 1, 1, 1]
])
attendance_percentage = np.mean(attendance, axis=1) * 100
print("Attendance percentage:", attendance_percentage)


Attendance percentage: [ 80.  40. 100.]


***16.A NumPy array contains ratings given by users. Write a program to normalize the ratings between 0 and 1.***




In [ ]:
ratings = np.array([1, 3, 4, 5, 2])
normalized = (ratings - np.min(ratings)) / (np.max(ratings) - np.min(ratings))
print("Normalized ratings:", normalized)


Normalized ratings: [0.   0.5  0.75 1.   0.25]


***17.Given a NumPy array of transaction amounts, write a program to flag suspicious transactions that are either extremely low or extremely high.***

In [10]:
transactions = np.array([200, 1500, 60000, 450, 30000, 100000])
suspicious = transactions[(transactions < 500) | (transactions > 50000)]
print("Suspicious transactions:", suspicious)


Suspicious transactions: [   200  60000    450 100000]


***18.A 2D NumPy array stores marks of students across tests. Write a program to identify the topper based on total marks***

In [11]:
marks = np.array([
    [80, 90, 85],
    [70, 75, 72],
    [95, 88, 92]
])
total_marks = np.sum(marks, axis=1)
topper = np.argmax(total_marks)
print("Total marks:", total_marks)
print("Topper student index:", topper)


Total marks: [255 217 275]
Topper student index: 2
