### **Numpy**

In [4]:
#numpy is a python library used for working with large multi dimentional arrey and mathematical function.

import numpy as np

In [5]:
arr= np.array([10,20,30])
print(arr*2)

[20 40 60]


In [6]:
a=[10,20,30]
print(a*2)

[10, 20, 30, 10, 20, 30]


In [7]:
#sclicing
#array[star:end]
arr=np.array([10,20,30,40])
print(arr[1:4])
print(arr[2:4])

[20 30 40]
[30 40]


**Numpy Function**

In [8]:
#numpy function
#1.arrange()
arr=np.arange(1,6)
print(arr)

[1 2 3 4 5]


In [9]:
#zeros()
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [10]:
#ones
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [11]:
#min(),sum(),mean(),max()
marks=np.array([10,20,30])
print("sum:",np.sum(marks))
print("Average:",np.mean(marks))
print("MAx:",np.max(marks))
print("Min:",np.min(marks))

sum: 60
Average: 20.0
MAx: 30
Min: 10


In [12]:
#1.Write a Python program to create a NumPy array with five integers and display it.
arr=np.array([1,2,3,5,6])
print(arr)

[1 2 3 5 6]


In [13]:
#2.Write a program to find the data type of a NumPy array.

arr=np.array([10,20,30])
print(arr.dtype)

int64


***2D numpy Array***


In [14]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


### ***2D Array accessing Elements***
array[Row_index,colunm_index]

In [15]:
print(arr[2,1])

80


## ***2D sclicing Numpy***
array[row_start:row_end,column_start:column_end]

In [23]:
arr=np.array([
    [10,20,30,53],
    [40,50,60,34],
    [70,80,90,56]
])
print(arr[1:4,0:5])

[[40 50 60 34]
 [70 80 90 56]]


In [24]:
print(arr*2)

[[ 20  40  60 106]
 [ 80 100 120  68]
 [140 160 180 112]]


In [25]:
#axis=0 /column
#axis=1/ row
marks=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print("Average Marks",np.mean(marks,axis=1))

Average Marks [20. 50. 80.]


In [26]:
print("Average Marks",np.mean(marks,axis=0))

Average Marks [40. 50. 60.]
